FROM python:3.10-slim

WORKDIR /app

# Install ffmpeg untuk konversi audio
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY backend/ .
COPY frontend/ ./frontend/

# Buat folder downloads
RUN mkdir -p downloads

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]